# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

all_keys = ("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S",
            "T", "U", "V", "W", "X", "Y", "Z", "Space", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0",
            ";", "'", "\\", ",", ".", "/", "[", "]", "~",
            )


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setMinimumSize(QtCore.QSize(922, 309))
        MainWindow.setMaximumSize(QtCore.QSize(922, 309))
        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 40, 786, 91))
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)

        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(130, 180, 312, 102))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)

        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 111, 91))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)

        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 180, 111, 101))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)

        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(480, 180, 111, 101))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)

        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(601, 180, 311, 102))
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)

        self.checkBox_1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_11 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_12 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_13 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_14 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_16 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_17 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_18 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)

        self.gridLayout.addWidget(self.checkBox_1, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.checkBox_3, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.checkBox_4, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.checkBox_5, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.checkBox_6, 1, 5, 1, 1)
        self.gridLayout.addWidget(self.checkBox_7, 1, 6, 1, 1)
        self.gridLayout.addWidget(self.checkBox_8, 1, 7, 1, 1)
        self.gridLayout.addWidget(self.checkBox_9, 1, 8, 1, 1)
        self.gridLayout.addWidget(self.checkBox_10, 1, 9, 1, 1)
        self.gridLayout_2.addWidget(self.checkBox_11, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.checkBox_12, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.checkBox_13, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.checkBox_14, 0, 3, 1, 1)
        self.gridLayout_6.addWidget(self.checkBox_15, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.checkBox_16, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.checkBox_17, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.checkBox_18, 0, 3, 1, 1)

        self.spinBox_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_5 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_6 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_7 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_8 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_9 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_10 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_11 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_12 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_13 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_14 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_15 = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_16 = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_17 = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_18 = QtWidgets.QSpinBox(self.gridLayoutWidget_6)

        self.gridLayout.addWidget(self.spinBox_1, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.spinBox_2, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.spinBox_3, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.spinBox_4, 3, 3, 1, 1)
        self.gridLayout.addWidget(self.spinBox_5, 3, 4, 1, 1)
        self.gridLayout.addWidget(self.spinBox_6, 3, 5, 1, 1)
        self.gridLayout.addWidget(self.spinBox_7, 3, 6, 1, 1)
        self.gridLayout.addWidget(self.spinBox_8, 3, 7, 1, 1)
        self.gridLayout.addWidget(self.spinBox_9, 3, 8, 1, 1)
        self.gridLayout.addWidget(self.spinBox_10, 3, 9, 1, 1)
        self.gridLayout_2.addWidget(self.spinBox_11, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.spinBox_12, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.spinBox_13, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.spinBox_14, 2, 3, 1, 1)
        self.gridLayout_6.addWidget(self.spinBox_15, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.spinBox_16, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.spinBox_17, 2, 2, 1, 1)
        self.gridLayout_6.addWidget(self.spinBox_18, 2, 3, 1, 1)

        self.comboBox_group = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_8 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_9 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_10 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_11 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_11_act = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_12 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_12_act = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_13 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_13_act = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_14 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_14_act = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_15 = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_15_act = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_16 = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_16_act = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_17 = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_17_act = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_18 = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_18_act = QtWidgets.QComboBox(self.gridLayoutWidget_6)

        self.comboBox_group.setGeometry(QtCore.QRect(446, 11, 101, 21))
        self.gridLayout.addWidget(self.comboBox_1, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.comboBox_3, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.comboBox_4, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.comboBox_5, 2, 4, 1, 1)
        self.gridLayout.addWidget(self.comboBox_6, 2, 5, 1, 1)
        self.gridLayout.addWidget(self.comboBox_7, 2, 6, 1, 1)
        self.gridLayout.addWidget(self.comboBox_8, 2, 7, 1, 1)
        self.gridLayout.addWidget(self.comboBox_9, 2, 8, 1, 1)
        self.gridLayout.addWidget(self.comboBox_10, 2, 9, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_11, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_11_act, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_12, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_12_act, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_13, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_13_act, 3, 2, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_14, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.comboBox_14_act, 3, 3, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_15, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_15_act, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_16, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_16_act, 3, 1, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_17, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_17_act, 3, 2, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_18, 1, 3, 1, 1)
        self.gridLayout_6.addWidget(self.comboBox_18_act, 3, 3, 1, 1)

        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)

        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 431, 21))
        self.label_5.setGeometry(QtCore.QRect(10, 149, 380, 21))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.label_12, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14.setGeometry(QtCore.QRect(480, 150, 421, 21))

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        global all_keys
        for i in all_keys:
            self.comboBox_1.addItem(f"{i}")
            self.comboBox_2.addItem(f"{i}")
            self.comboBox_3.addItem(f"{i}")
            self.comboBox_4.addItem(f"{i}")
            self.comboBox_5.addItem(f"{i}")
            self.comboBox_6.addItem(f"{i}")
            self.comboBox_7.addItem(f"{i}")
            self.comboBox_8.addItem(f"{i}")
            self.comboBox_9.addItem(f"{i}")
            self.comboBox_10.addItem(f"{i}")
            self.comboBox_11.addItem(f"{i}")
            self.comboBox_12.addItem(f"{i}")
            self.comboBox_13.addItem(f"{i}")
            self.comboBox_14.addItem(f"{i}")
            self.comboBox_15.addItem(f"{i}")
            self.comboBox_16.addItem(f"{i}")
            self.comboBox_17.addItem(f"{i}")
            self.comboBox_18.addItem(f"{i}")
            self.comboBox_11_act.addItem(f"{i}")
            self.comboBox_12_act.addItem(f"{i}")
            self.comboBox_13_act.addItem(f"{i}")
            self.comboBox_14_act.addItem(f"{i}")
            self.comboBox_15_act.addItem(f"{i}")
            self.comboBox_16_act.addItem(f"{i}")
            self.comboBox_17_act.addItem(f"{i}")
            self.comboBox_18_act.addItem(f"{i}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кликер"))
        self.label.setText(_translate("MainWindow", "Выбрать"))
        self.label_2.setText(_translate("MainWindow", "Тайминг в мс"))
        self.label_3.setText(_translate("MainWindow", "Клавиша"))
        self.label_4.setText(_translate("MainWindow", "Групповая активация нескольких клавиш после нажатия"))
        self.label_5.setText(_translate("MainWindow", "Активация клавиш по отдельности без удержания"))
        self.label_6.setText(_translate("MainWindow", "Клавиша"))
        self.label_7.setText(_translate("MainWindow", "Тайминг в мс"))
        self.label_8.setText(_translate("MainWindow", "Активатор"))
        self.label_9.setText(_translate("MainWindow", "Выбрать"))
        self.label_10.setText(_translate("MainWindow", "Тайминг в мс"))
        self.label_11.setText(_translate("MainWindow", "Клавиша"))
        self.label_12.setText(_translate("MainWindow", "Активатор"))
        self.label_13.setText(_translate("MainWindow", "Выбрать"))
        self.label_14.setText(_translate("MainWindow", "Активация клавиш по отдельности при удержании"))
